name: Build Android MAUI

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore Workloads
      run: dotnet workload restore CVGenerator.csproj

    - name: Restore Dependencies
      run: dotnet restore CVGenerator.csproj

    - name: Build Android APK
      run: dotnet publish CVGenerator.csproj -f net8.0-android -c Debug /p:AndroidPackageFormat=apk

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: CVGenerator-Android-App
        path: '**/*Signed.apk'
